service: node-keeper-unfurl-serverless-app

custom:
  secrets: ${file(serviceAccountKey.json)}

provider: 
  name: aws
  stackName: kometa-keeper-unfurl-stack
  apiName: kometa-keeper-unfurl-api
  runtime: nodejs14.x
  stage: ${env:STAGE}
  region: eu-central-1 

functions: 
  app: 
    handler: app.handler 
    events:
      - http: 
          path: /logkeeper/unfurl 
          method: get

plugins:
  - serverless-offline
  - serverless-dotenv-plugin