service: node-keeper-back-serverless-app

custom:
  secrets: ${file(serviceAccountKey.json)}
  slack_enable_logging: true

provider: 
  name: aws
  stackName: kometa-keeper-back-stack
  apiName: kometa-keeper-back-api
  runtime: nodejs14.x
  stage: ${env:STAGE}
  region: eu-central-1
  memorySize: 1024
  timeout: 8
  environment:
    VERIFICATION_TOKEN: ${env:VERIFICATION_TOKEN}
    URL_FORMAT: ${env:URL_FORMAT}

functions: 
  app: 
    handler: app.handler 
    events:
      - http:
          path: /keeper-save
          method: post

plugins:
  - serverless-offline
  - serverless-dotenv-plugin